// Code generated by github.com/bckground/go-options. DO NOT EDIT.
// Source: formatConfig{}
//
// Generated by this command:
//
//	go-options -new=false -namespace=FormatOptions -option=FormatOption -output=zz_generated.formatconfig.options.go formatConfig
//

package tomledit

import "fmt"

import "github.com/google/go-cmp/cmp"

type ApplyFormatOptionFunc func(c *formatConfig) error

func (f ApplyFormatOptionFunc) apply(c *formatConfig) error {
	return f(c)
}

func applyFormatConfigOptions(c *formatConfig, options ...FormatOption) error {
	for _, o := range options {
		if err := o.apply(c); err != nil {
			return err
		}
	}
	return nil
}

type FormatOption interface {
	apply(*formatConfig) error
}

type formatOptionNamespace struct{}

var FormatOptions formatOptionNamespace

type formatOptionIndentImpl struct {
	o int
}

func (o formatOptionIndentImpl) apply(c *formatConfig) error {
	c.Indent = o.o
	return nil
}

func (o formatOptionIndentImpl) Equal(v formatOptionIndentImpl) bool {
	switch {
	case !cmp.Equal(o.o, v.o):
		return false
	}
	return true
}

func (o formatOptionIndentImpl) String() string {
	name := "Indent"

	// hack to avoid go vet error about passing a function to Sprintf
	var value interface{} = o.o
	return fmt.Sprintf("%s: %+v", name, value)
}

func (formatOptionNamespace) Indent(o int) FormatOption {
	return formatOptionIndentImpl{
		o: o,
	}
}
